# Generated by Django 4.2.1 on 2023-09-28 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
